Repository atharvatechnology/apex-backend, pull requests merged in 2022-12, with the labels that each got.

#342 roles has M2M, new roles defined and custom migrations
  accounts/admin.py
  accounts/api/serializers.py
  accounts/api/views.py
  accounts/migrations/0015_auto_20221122_1443.py
  accounts/migrations/0016_auto_20221122_1509.py
  accounts/migrations/0017_remove_user_role.py
  accounts/models.py
  payments/api/views.py
Labels: enhancement :fire: :fire:

#357 Enable load testing with locust.
  .gitignore
  .isort.cfg
  CI/__init__.py
  CI/create_dummies.py
  CI/delete_dummies.py
  CI/locustfile.py
Labels: enhancement :fire: :fire:, deployment :flight_departure:

#349 Attendance
  apex/urls.py
  attendance/admin.py
  attendance/api/serializers.py
  attendance/api/urls.py
  attendance/api/views.py
  attendance/api_admin/__init__.py
  attendance/api_admin/serializers.py
  attendance/api_admin/urls.py
  attendance/api_admin/views.py
  attendance/filters.py
  attendance/migrations/0006_auto_20221129_1540.py
  attendance/migrations/0007_auto_20221130_1144.py
  attendance/migrations/0008_auto_20221201_1702.py
  attendance/migrations/0009_auto_20221201_1705.py
  attendance/migrations/0010_alter_teacherattendancedetail_number_of_period.py
  attendance/migrations/0011_alter_attendance_date.py
  attendance/migrations/0012_alter_attendance_date.py
  attendance/migrations/0013_alter_attendance_date.py
  attendance/models.py
Labels: enhancement :fire: :fire:

#356 Graph API required for Admin Dashboard
  apex/settings.py
  apex/urls.py
  courses/admin.py
  dashboard/__init__.py
  dashboard/api_admin/__init__.py
  dashboard/api_admin/filters.py
  dashboard/api_admin/serializers.py
  dashboard/api_admin/urls.py
  dashboard/api_admin/views.py
  dashboard/apps.py
  dashboard/migrations/__init__.py
  exams/admin.py
Labels: enhancement :fire: :fire:

#359 Add filter price choice, is_published in exam list
  exams/filters.py
Labels: enhancement :fire: :fire:

#363 price choice changed
  exams/filters.py
Labels: enhancement :fire: :fire:

#364 Deploy
  .github/workflows/deploy-gcp.yml
  exams/filters.py
Labels: deployment :flight_departure:

#366 Add admin views for dashboard, exam, course.
  accounts/api/serializers.py
  accounts/api/views.py
  courses/api_admin/serializers.py
  courses/api_admin/urls.py
  courses/api_admin/views.py
  courses/filters.py
  dashboard/api_admin/views.py
  enrollments/api_admin/serializers.py
  exams/api_admin/serializers.py
  exams/api_admin/urls.py
  exams/api_admin/views.py
  exams/filters.py
  notes/api_admin/serializers.py
  notes/api_admin/views.py
  notes/migrations/0009_content_is_downloadable.py
  notes/models.py
Labels: enhancement :fire: :fire:

#367 deployment
  .github/workflows/deploy-gcp.yml
  .github/workflows/gcloud-upscale.yml
  .github/workflows/glcoud-downscale.yml
  accounts/api/serializers.py
  accounts/api/views.py
  courses/api_admin/serializers.py
  courses/api_admin/urls.py
  courses/api_admin/views.py
  courses/filters.py
  dashboard/api_admin/views.py
  enrollments/api_admin/serializers.py
  exams/api_admin/serializers.py
  exams/api_admin/urls.py
  exams/api_admin/views.py
  exams/filters.py
  notes/api_admin/serializers.py
  notes/api_admin/views.py
  notes/migrations/0009_content_is_downloadable.py
  notes/models.py
Labels: deployment :flight_departure:

#361 Enable update and delete for enrollments.
  .pre-commit-config.yaml
  courses/api_admin/views.py
  courses/filters.py
  enrollments/api/views.py
  enrollments/api_admin/urls.py
  exams/api/serializers.py
  exams/filters.py
Labels: enhancement :fire: :fire:

#370 Accounts api admin list update
  accounts/api_admin/filters.py
  accounts/api_admin/serializers.py
  accounts/api_admin/urls.py
  accounts/api_admin/views.py
  accounts/filters.py
  accounts/migrations/0018_profile_interests.py
  accounts/migrations/0019_alter_profile_interests.py
  accounts/models.py
Labels: enhancement :fire: :fire:

#371 Counselor filter and serializer fix
  accounts/api_admin/urls.py
  accounts/api_admin/views.py
  counseling/api_admin/serializers.py
  counseling/filters.py
Labels: enhancement :fire: :fire:

#365 CRUD Operations for PhysicalBook for Admin.
  apex/urls.py
  courses/api_common/serializers.py
  enrollments/api/urls.py
  enrollments/api/views.py
  enrollments/api_admin/serializers.py
  enrollments/api_admin/urls.py
  enrollments/api_admin/views.py
  physicalbook/api/serializers.py
  physicalbook/api/urls.py
  physicalbook/api/views.py
  physicalbook/api_admin/__init__.py
  physicalbook/api_admin/serializers.py
  physicalbook/api_admin/urls.py
  physicalbook/api_admin/views.py
Labels: enhancement :fire: :fire:

#355 Enrollment and exam flow for practice exam.
  common/models.py
  enrollments/api/serializers.py
  enrollments/api/utils.py
  enrollments/models.py
  enrollments/signals.py
  enrollments/tasks.py
  exams/api/urls.py
  exams/api/views.py
  exams/models.py
Labels: enhancement :fire: :fire:

#372 Optimize deployments by reducing gunicorn workers.
  gunicorn-config.py
Labels: enhancement :fire: :fire:, deployment :flight_departure:

#374 Admin Api check and fix with frontend
  accounts/api_admin/serializers.py
  accounts/api_admin/urls.py
  accounts/api_admin/views.py
  enrollments/api_admin/serializers.py
  enrollments/api_admin/urls.py
  enrollments/api_admin/views.py
  enrollments/filters.py
  notifications/api_admin/serializers.py
  notifications/api_admin/views.py
Labels: enhancement :fire: :fire:

#375 Deployment
  .github/workflows/gcloud-upscale.yml
  .github/workflows/glcoud-downscale.yml
  .pre-commit-config.yaml
  accounts/api_admin/filters.py
  accounts/api_admin/serializers.py
  accounts/api_admin/urls.py
  accounts/api_admin/views.py
  accounts/filters.py
  accounts/migrations/0018_profile_interests.py
  accounts/migrations/0019_alter_profile_interests.py
  accounts/models.py
  apex/urls.py
  common/models.py
  counseling/api_admin/serializers.py
  counseling/filters.py
  courses/api_admin/serializers.py
  courses/api_admin/urls.py
  courses/api_admin/views.py
  courses/api_common/serializers.py
  courses/filters.py
  enrollments/api/serializers.py
  enrollments/api/urls.py
  enrollments/api/utils.py
  enrollments/api/views.py
  enrollments/api_admin/serializers.py
  enrollments/api_admin/urls.py
  enrollments/api_admin/views.py
  enrollments/filters.py
  enrollments/models.py
  enrollments/signals.py
  enrollments/tasks.py
  exams/api/serializers.py
  exams/api/urls.py
  exams/api/views.py
  exams/filters.py
  exams/models.py
  gunicorn-config.py
  notifications/api_admin/serializers.py
  notifications/api_admin/views.py
  physicalbook/api/serializers.py
  physicalbook/api/urls.py
  physicalbook/api/views.py
  physicalbook/api_admin/__init__.py
  physicalbook/api_admin/serializers.py
  physicalbook/api_admin/urls.py
  physicalbook/api_admin/views.py
Labels: deployment :flight_departure:

#377 deployment
  .github/workflows/main.yml
  enrollments/api_admin/serializers.py
Labels: deployment :flight_departure:

#378 Physical book pagination and issue part
  apex/urls.py
  courses/api_admin/serializers.py
  courses/api_admin/urls.py
  courses/api_admin/views.py
  enrollments/admin.py
  notes/api_admin/serializers.py
  notes/api_admin/urls.py
  notes/api_admin/views.py
  physicalbook/api_admin/serializers.py
  physicalbook/api_admin/urls.py
  physicalbook/api_admin/views.py
Labels: enhancement :fire: :fire:

#379 Deployment
  apex/urls.py
  courses/api_admin/serializers.py
  courses/api_admin/urls.py
  courses/api_admin/views.py
  enrollments/admin.py
  notes/api_admin/serializers.py
  notes/api_admin/urls.py
  notes/api_admin/views.py
  physicalbook/api_admin/serializers.py
  physicalbook/api_admin/urls.py
  physicalbook/api_admin/views.py
Labels: deployment :flight_departure:

#380 enrollment bug fix
  accounts/models.py
  enrollments/api_admin/serializers.py
Labels: enhancement :fire: :fire:

#381 Deployment
  accounts/models.py
  enrollments/api_admin/serializers.py
Labels: deployment :flight_departure:

#383 Attendance and notification fix
  attendance/admin.py
  attendance/api_admin/serializers.py
  attendance/api_admin/urls.py
  attendance/api_admin/views.py
  attendance/filters.py
  attendance/models.py
  notifications/api_admin/serializers.py
  notifications/api_admin/views.py
Labels: enhancement :fire: :fire:

#385 Add trend in revenue overview dashboard
  dashboard/api_admin/serializers.py
  dashboard/api_admin/urls.py
  dashboard/api_admin/views.py
Labels: enhancement :fire: :fire:
