Repository atharvatechnology/apex-backend, pull requests merged in 2022-11, with the labels that each got.

#322 Create exam and course enrollments in admin dashboard.
  courses/api_admin/serializers.py
  courses/api_admin/urls.py
  courses/api_admin/views.py
  courses/api_common/serializers.py
  enrollments/api_admin/serializers.py
  enrollments/api_admin/urls.py
  enrollments/api_admin/views.py
  enrollments/filters.py
  enrollments/migrations/0042_alter_coursethroughenrollment_completed_date.py
  enrollments/models.py
  exams/api_admin/serializers.py
  exams/api_admin/urls.py
  exams/api_admin/views.py
  exams/api_common/__init__.py
  exams/api_common/serializers.py
  payments/api_common/serializers.py
Labels: enhancement :fire: :fire:

#326 Revenue list for admin with date range and date from to filter
  .isort.cfg
  accounts/api/serializers.py
  apex/urls.py
  enrollments/api/serializers.py
  payments/api_admin/__init__.py
  payments/api_admin/filters.py
  payments/api_admin/serializers.py
  payments/api_admin/urls.py
  payments/api_admin/views.py
Labels: enhancement :fire: :fire:

#327 Deploy
  .isort.cfg
  accounts/api/serializers.py
  accounts/api/urls.py
  accounts/api/views.py
  accounts/filters.py
  apex/settings.py
  apex/urls.py
  attendance/api/serializers.py
  attendance/api/urls.py
  attendance/api/views.py
  common/api/serializers.py
  common/api/views.py
  common/report.py
  common/utils.py
  courses/api_admin/serializers.py
  courses/api_admin/urls.py
  courses/api_admin/views.py
  courses/api_common/serializers.py
  enrollments/api/serializers.py
  enrollments/api/tasks.py
  enrollments/api/urls.py
  enrollments/api/views.py
  enrollments/api_admin/serializers.py
  enrollments/api_admin/urls.py
  enrollments/api_admin/views.py
  enrollments/filters.py
  enrollments/migrations/0042_alter_coursethroughenrollment_completed_date.py
  enrollments/models.py
  exams/api/views.py
  exams/api_admin/serializers.py
  exams/api_admin/urls.py
  exams/api_admin/views.py
  exams/api_common/__init__.py
  exams/api_common/serializers.py
  exams/filters.py
  payments/api/serializers.py
  payments/api/urls.py
  payments/api/views.py
  payments/api_admin/__init__.py
  payments/api_admin/filters.py
  payments/api_admin/serializers.py
  payments/api_admin/urls.py
  payments/api_admin/views.py
  payments/api_common/serializers.py
  payments/filters.py
  report/__init__.py
  report/admin.py
  report/apps.py
  report/migrations/0001_initial.py
  report/migrations/0002_alter_generatedreport_report_file.py
  report/migrations/__init__.py
  report/models.py
  report/tabledata.py
  report/tests.py
  report/views.py
  requirements.txt
Labels: deployment :flight_departure:

#332 update profile field for admin
  accounts/api_admin/serializers.py
Labels: enhancement :fire: :fire:

#333 swagger initial error
  attendance/api/views.py
  common/utils.py
Labels: enhancement :fire: :fire:

#329 Update and delete enrollment by admin.
  .gitignore
  accounts/admin.py
  enrollments/admin.py
  enrollments/api_admin/serializers.py
  enrollments/api_admin/urls.py
  enrollments/api_admin/views.py
  exams/api/serializers.py
  exams/api/views.py
  exams/api_admin/serializers.py
  exams/migrations/0026_exam_exam_type.py
  exams/migrations/0027_auto_20221110_1724.py
  exams/migrations/0028_auto_20221110_1736.py
  exams/models.py
Labels: enhancement :fire: :fire:

#334 Deploy
  .gitignore
  accounts/admin.py
  accounts/api_admin/serializers.py
  attendance/api/views.py
  common/utils.py
  enrollments/admin.py
  enrollments/api_admin/serializers.py
  enrollments/api_admin/urls.py
  enrollments/api_admin/views.py
  enrollments/filters.py
  exams/api/serializers.py
  exams/api/views.py
  exams/api_admin/serializers.py
  exams/migrations/0026_exam_exam_type.py
  exams/migrations/0027_auto_20221110_1724.py
  exams/migrations/0028_auto_20221110_1736.py
  exams/models.py
  payments/api/urls.py
  payments/api/views.py
Labels: deployment :flight_departure:

#345 Implement practice exam feature.
  enrollments/api/serializers.py
  enrollments/api/urls.py
  enrollments/api/utils.py
  enrollments/api/views.py
  exams/api/serializers.py
  exams/api/views.py
  infocenter/admin.py
  infocenter/api/serializers.py
  infocenter/api/urls.py
  infocenter/api/views.py
  infocenter/api_admin/serializers.py
  infocenter/api_admin/urls.py
  infocenter/api_admin/views.py
  infocenter/migrations/0003_webresouce.py
  infocenter/models.py
  payments/signals.py
Labels: feature :new:

#338 Create Counseling Model.
  apex/settings.py
  apex/urls.py
  counseling/__init__.py
  counseling/admin.py
  counseling/api_admin/__init__.py
  counseling/api_admin/serializers.py
  counseling/api_admin/urls.py
  counseling/api_admin/views.py
  counseling/apps.py
  counseling/filters.py
  counseling/migrations/0001_initial.py
  counseling/migrations/0002_auto_20221116_1613.py
  counseling/migrations/0003_alter_counseling_options.py
  counseling/migrations/0004_rename_date_counseling_created_at.py
  counseling/migrations/0005_alter_counseling_created_at.py
  counseling/migrations/0006_alter_counseling_note.py
  counseling/migrations/0007_alter_counseling_note.py
  counseling/migrations/__init__.py
  counseling/models.py
  counseling/tests.py
  counseling/views.py
Labels: feature :new:

#337 Exam enrollment inside course
  courses/api/urls.py
  courses/api_admin/views.py
  courses/migrations/0011_auto_20221116_1635.py
  courses/models.py
  enrollments/api/serializers.py
  enrollments/api/views.py
  exams/filters.py
Labels: enhancement :fire: :fire:

#346 Info center webresource naming fix
  infocenter/admin.py
  infocenter/api/serializers.py
  infocenter/api/urls.py
  infocenter/api/views.py
  infocenter/api_admin/serializers.py
  infocenter/api_admin/urls.py
  infocenter/api_admin/views.py
  infocenter/migrations/0003_webresource.py
  infocenter/models.py
Labels: enhancement :fire: :fire:

#348 Update filters
  counseling/filters.py
Labels: enhancement :fire: :fire:

#344 Banner ads
  apex/settings.py
  apex/urls.py
  bannerad/__init__.py
  bannerad/admin.py
  bannerad/api/__init__.py
  bannerad/api/serializers.py
  bannerad/api/urls.py
  bannerad/api/views.py
  bannerad/api_admin/__init__.py
  bannerad/api_admin/serializers.py
  bannerad/api_admin/urls.py
  bannerad/api_admin/views.py
  bannerad/apps.py
  bannerad/migrations/0001_initial.py
  bannerad/migrations/0002_auto_20221124_1344.py
  bannerad/migrations/0003_alter_bannerad_img.py
  bannerad/migrations/0004_alter_bannerad_options.py
  bannerad/migrations/__init__.py
  bannerad/models.py
  bannerad/tests.py
  bannerad/views.py
Labels: enhancement :fire: :fire:
