Repository atharvatechnology/apex-backend, pull requests merged in 2022-06, with the labels that each got.

#85 Added New SMS platform and made both work
  accounts/api/otp.py
  apex/.env.template
  apex/settings.py
Labels: enhancement :fire: :fire:

#88 Retrieve exam enrollment on exam retrieve.
  enrollments/tasks.py
  exams/api/serializers.py
Labels: enhancement :fire: :fire:

#89 Smsplatform
  .isort.cfg
  accounts/api/otp.py
  accounts/api/serializers.py
  apex/settings.py
Labels: bug :bug:

#42 Add Crud for courses.
  apex/settings.py
  apex/urls.py
  courses/admin.py
  courses/api/paginations.py
  courses/api/serializers.py
  courses/api/urls.py
  courses/api/views.py
  courses/filters.py
  courses/migrations/0002_remove_course_instructor_id_remove_course_type_id.py
  courses/models.py
Labels: enhancement :fire: :fire:

#96 Admin panel customization for auto createdby and updatedby
  common/admin.py
  enrollments/admin.py
  exams/admin.py
  notes/admin.py
Labels: enhancement :fire: :fire:

#99 User model Group Formulate
  accounts/admin.py
Labels: bug :bug:

#101 ckeditor and admin panel fix
  .gitignore
  .isort.cfg
  apex/settings.py
  enrollments/admin.py
  exams/migrations/0007_alter_question_detail.py
  exams/migrations/0008_alter_option_detail.py
  exams/models.py
  requirements.txt
Labels: enhancement :fire: :fire:, feature :new:

#106 Handle enrollment and session states.
  .isort.cfg
  apex/settings.py
  common/errors.py
  enrollments/api/serializers.py
  enrollments/api/views.py
  enrollments/migrations/0007_alter_questionenrollment_selected_option.py
  enrollments/migrations/0008_auto_20220603_0945.py
  enrollments/migrations/0009_alter_examthroughenrollment_status.py
  enrollments/models.py
  enrollments/signals.py
  enrollments/tasks.py
  exams/admin.py
  exams/api/views.py
  exams/migrations/0007_alter_exam_status.py
  exams/migrations/0008_alter_examtemplate_duration.py
  exams/migrations/0009_merge_20220603_1720.py
  exams/models.py
Labels: enhancement :fire: :fire:

#105 Server email, option limit to 4
  apex/.env.template
  apex/middleware.py
  apex/settings.py
  exams/admin.py
Labels: enhancement :fire: :fire:

#112 Enrollments
  enrollments/api/serializers.py
  enrollments/api/urls.py
  enrollments/api/views.py
  enrollments/models.py
  exams/api/permissions.py
  exams/api/views.py
  exams/models.py
Labels: enhancement :fire: :fire:

#113 Pooling in examenrollment, examresult
  enrollments/admin.py
  enrollments/api/serializers.py
  enrollments/api/urls.py
  enrollments/api/views.py
  exams/api/serializers.py
  exams/api/urls.py
  exams/api/views.py
Labels: enhancement :fire: :fire:

#117 User auto login after signup and reset password
  accounts/api/serializers.py
  accounts/api/views.py
Labels: enhancement :fire: :fire:

#116 Add note views and serializers for course retrive
  courses/admin.py
  courses/api/serializers.py
  courses/api/urls.py
  courses/api/views.py
  notes/api/serializers.py
  notes/api/urls.py
  notes/api/views.py
  notes/migrations/0002_note_course_id.py
  notes/migrations/0003_alter_note_course_id.py
  notes/migrations/0004_alter_content_note.py
  notes/migrations/0005_rename_course_id_note_course.py
  notes/migrations/0006_alter_content_note.py
  notes/models.py
  notes/tests.py
  notes/tests/__init__.py
  notes/tests/test_forms.py
  notes/tests/test_models.py
  notes/tests/test_views.py
Labels: enhancement :fire: :fire:

#124 Percentage field for pass_marks and negative marks
  common/modelFields.py
  enrollments/models.py
  enrollments/tasks.py
  exams/admin.py
  exams/api/serializers.py
  exams/migrations/0010_examtemplate_pass_percentage.py
  exams/migrations/0011_auto_20220608_1342.py
  exams/migrations/0012_auto_20220608_1350.py
  exams/migrations/0013_auto_20220608_1354.py
  exams/migrations/0014_auto_20220608_1355.py
  exams/migrations/0015_remove_section_neg_marks.py
  exams/models.py
Labels: enhancement :fire: :fire:

#132 Add physical book model, crud and also nested serializer for course
  apex/settings.py
  apex/urls.py
  courses/api/serializers.py
  courses/migrations/0003_alter_course_options.py
  courses/models.py
  notes/api/serializers.py
  physicalbook/__init__.py
  physicalbook/admin.py
  physicalbook/api/serializers.py
  physicalbook/api/urls.py
  physicalbook/api/views.py
  physicalbook/apps.py
  physicalbook/migrations/0001_initial.py
  physicalbook/migrations/0002_auto_20220608_1534.py
  physicalbook/migrations/__init__.py
  physicalbook/models.py
  physicalbook/tests.py
  physicalbook/views.py
Labels: enhancement :fire: :fire:

#143 Bug:Admin panel Exam creadted_by and updated_by auto
  exams/admin.py
Labels: bug :bug:

#146 Add and broadcast FSM for course enrollments.
  .isort.cfg
  apex/asgi.py
  apex/settings.py
  clock/__init__.py
  clock/admin.py
  clock/apps.py
  clock/consumers.py
  clock/migrations/__init__.py
  clock/models.py
  clock/routing.py
  clock/tests.py
  clock/views.py
  enrollments/api/views.py
  enrollments/migrations/0012_alter_session_status.py
  enrollments/models.py
  enrollments/signals.py
  enrollments/tasks.py
  requirements.txt
Labels: enhancement :fire: :fire:

#147 Fix settings not found in asgi.
  apex/asgi.py
Labels: bug :bug:

#150 dev environment
  Dockerfile
Labels: deployment :flight_departure:

#155 Add publishable feature to user facing content.
  common/api/mixin.py
  common/models.py
  enrollments/admin.py
  enrollments/api/views.py
  enrollments/migrations/0013_auto_20220614_1040.py
  enrollments/migrations/0014_auto_20220614_1051.py
  enrollments/models.py
Labels: enhancement :fire: :fire:

#156 Dev
  common/api/mixin.py
  common/models.py
  enrollments/admin.py
  enrollments/api/views.py
  enrollments/migrations/0013_auto_20220614_1040.py
  enrollments/migrations/0014_auto_20220614_1051.py
  enrollments/models.py
Labels: deployment :flight_departure:

#133 Add models to enrollments apps
  .github/workflows/main.yml
  enrollments/migrations/0012_auto_20220609_1648.py
  enrollments/migrations/0013_merge_20220613_1556.py
  enrollments/migrations/0014_auto_20220613_1605.py
  enrollments/migrations/0015_alter_examthroughenrollment_selected_session.py
  enrollments/migrations/0016_alter_physicalbookcourseenrollment_course_enrollment.py
  enrollments/migrations/0017_auto_20220615_1106.py
  enrollments/migrations/0018_auto_20220615_1214.py
  enrollments/models.py
  physicalbook/models.py
Labels: enhancement :fire: :fire:

#159 Add User Profile and Update User Create Serializer.
  accounts/admin.py
  accounts/api/serializers.py
  accounts/apps.py
  accounts/migrations/0005_profile.py
  accounts/migrations/0006_auto_20220616_1005.py
  accounts/models.py
  accounts/signals.py
  common/decorators.py
  enrollments/migrations/0014_auto_20220614_1051.py
  enrollments/migrations/0019_merge_0014_auto_20220614_1051_0018_auto_20220615_1214.py
Labels: enhancement :fire: :fire:

#128 Attendance model,with student and teacher inheritated from it
  apex/settings.py
  attendance/__init__.py
  attendance/admin.py
  attendance/apps.py
  attendance/migrations/0001_initial.py
  attendance/migrations/0002_auto_20220607_1517.py
  attendance/migrations/0003_remove_attendance_category.py
  attendance/migrations/__init__.py
  attendance/models.py
Labels: feature :new:

#161 Date hierarchy, img in admin panel
  enrollments/admin.py
  exams/admin.py
Labels: enhancement :fire: :fire:

#162 Dev
  accounts/admin.py
  accounts/api/serializers.py
  accounts/apps.py
  accounts/migrations/0005_profile.py
  accounts/migrations/0006_auto_20220616_1005.py
  accounts/models.py
  accounts/signals.py
  common/decorators.py
  enrollments/admin.py
  enrollments/migrations/0012_auto_20220609_1648.py
  enrollments/migrations/0013_merge_20220613_1556.py
  enrollments/migrations/0014_auto_20220613_1605.py
  enrollments/migrations/0014_auto_20220614_1051.py
  enrollments/migrations/0015_alter_examthroughenrollment_selected_session.py
  enrollments/migrations/0016_alter_physicalbookcourseenrollment_course_enrollment.py
  enrollments/migrations/0017_auto_20220615_1106.py
  enrollments/migrations/0018_auto_20220615_1214.py
  enrollments/migrations/0019_merge_0014_auto_20220614_1051_0018_auto_20220615_1214.py
  enrollments/models.py
  exams/admin.py
  physicalbook/models.py
Labels: deployment :flight_departure:

#163 Admin of user, ckeditor, preview exam feature
  accounts/admin.py
  apex/settings.py
  exams/api/urls.py
  exams/api/views.py
Labels: enhancement :fire: :fire:

#165 Filter Option by Exam
  exams/admin.py
Labels: enhancement :fire: :fire:

#166 Dev
  exams/admin.py
Labels: deployment :flight_departure:

#167 Show result publication date.
  enrollments/api/views.py
Labels: enhancement :fire: :fire:

#168 User add address field
  accounts/admin.py
  accounts/migrations/0007_profile_address.py
  accounts/models.py
  exams/admin.py
Labels: enhancement :fire: :fire:

#169 Dev
  accounts/admin.py
  accounts/migrations/0007_profile_address.py
  accounts/models.py
  enrollments/api/views.py
  exams/admin.py
Labels: deployment :flight_departure:

#170 Fix a typo.
  enrollments/api/views.py
Labels: bug :bug:

#171 Dev
  enrollments/api/views.py
Labels: deployment :flight_departure:

#172 Compare publish date to current local time.
  common/models.py
Labels: bug :bug:

#173 Dev
  common/models.py
Labels: deployment :flight_departure:

#174 Show result publish date in nepal time.
  enrollments/api/views.py
Labels: bug :bug:

#175 Dev
  enrollments/api/views.py
Labels: deployment :flight_departure:

#176 Brodcast result publish state.
  clock/consumers.py
  enrollments/signals.py
Labels: bug :bug:

#177 Dev
  clock/consumers.py
  enrollments/signals.py
Labels: deployment :flight_departure:

#178 Admin Panel Show clear data
  accounts/admin.py
  enrollments/admin.py
  exams/admin.py
Labels: enhancement :fire: :fire:

#179 Dev
  accounts/admin.py
  enrollments/admin.py
  exams/admin.py
Labels: deployment :flight_departure:

#180 Add exam template crud for admin panel
  exams/admin.py
  exams/api/serializers.py
  exams/api/urls.py
  exams/api/views.py
  exams/migrations/0016_examtemplate_description.py
  exams/migrations/0017_alter_section_template.py
  exams/migrations/0018_examtemplate_status.py
  exams/migrations/0019_auto_20220624_1549.py
  exams/models.py
Labels: enhancement :fire: :fire:

#181 Dev
  exams/admin.py
  exams/api/serializers.py
  exams/api/urls.py
  exams/api/views.py
  exams/migrations/0016_examtemplate_description.py
  exams/migrations/0017_alter_section_template.py
  exams/migrations/0018_examtemplate_status.py
  exams/migrations/0019_auto_20220624_1549.py
  exams/models.py
Labels: deployment :flight_departure:

#182 Make session dates uneditable after creation.
  enrollments/models.py
Labels: bug :bug:

#183 Dev
  enrollments/models.py
Labels: deployment :flight_departure:

#184 Refactor exam api.
  apex/urls.py
  exams/api/serializers.py
  exams/api/urls.py
  exams/api/views.py
  exams/api_admin/__init__.py
  exams/api_admin/serializers.py
  exams/api_admin/urls.py
  exams/api_admin/validators.py
  exams/api_admin/views.py
  exams/models.py
Labels: enhancement :fire: :fire:

#157 Add crud for physicalbook and CourseThroughEnrollment
  .gitignore
  courses/admin.py
  courses/migrations/0004_alter_coursecategory_options.py
  courses/models.py
  enrollments/admin.py
  enrollments/api/serializers.py
  enrollments/api/urls.py
  enrollments/api/views.py
  enrollments/migrations/0020_alter_coursethroughenrollment_options.py
  enrollments/migrations/0021_auto_20220629_1419.py
  enrollments/models.py
Labels: enhancement :fire: :fire:
