Repository atharvatechnology/apex-backend, pull requests merged in 2022-08, with the labels that each got.

#220 CRUD for accounts admin.
  accounts/api_admin/__init__.py
  accounts/api_admin/serializers.py
  accounts/api_admin/urls.py
  accounts/api_admin/views.py
  accounts/filters.py
  apex/settings.py
  apex/urls.py
  attendance/__init__.py
  attendance/admin.py
  attendance/api/__init__.py
  attendance/api/migrations/__init__.py
  attendance/api/serializers.py
  attendance/api/tests.py
  attendance/api/urls.py
  attendance/api/views.py
  attendance/apps.py
  attendance/filters.py
  attendance/migrations/0001_initial.py
  attendance/migrations/0002_auto_20220607_1517.py
  attendance/migrations/0003_remove_attendance_category.py
  attendance/migrations/0004_rename_number_of_peroid_teacherattendancedetail_number_of_period.py
  attendance/migrations/0005_auto_20220627_1659.py
  attendance/migrations/__init__.py
  attendance/models.py
  common/utils.py
  courses/api/serializers.py
  courses/filters.py
Labels: enhancement :fire: :fire:

#222 Add paginations to UserListAdminAPIView.
  accounts/api_admin/views.py
Labels: enhancement :fire: :fire:

#223 Add paginations.py in common.
  accounts/api_admin/views.py
  attendance/api/views.py
  common/paginations.py
  courses/api/views.py
  courses/api_admin/views.py
  exams/api/views.py
  exams/api_admin/views.py
  notes/api_admin/views.py
Labels: enhancement :fire: :fire:

#224 bug fix of missing pagination
  enrollments/api_admin/views.py
Labels: bug :bug:

#221 Make session extendable to exam / course sessions.
  enrollments/admin.py
  enrollments/api/serializers.py
  enrollments/api/views.py
  enrollments/api_admin/serializers.py
  enrollments/migrations/0026_examsession.py
  enrollments/migrations/0027_auto_20220728_1202.py
  enrollments/migrations/0028_remove_session_exam.py
  enrollments/migrations/0029_auto_20220728_1218.py
  enrollments/migrations/0030_auto_20220728_1520.py
  enrollments/migrations/0031_alter_examsession_options.py
  enrollments/migrations/0032_auto_20220728_1803.py
  enrollments/migrations/0033_auto_20220728_1826.py
  enrollments/migrations/0034_alter_examsession_exam.py
  enrollments/migrations/0035_coursesession.py
  enrollments/migrations/0036_alter_examthroughenrollment_selected_session.py
  enrollments/migrations/0037_alter_coursethroughenrollment_selected_session.py
  enrollments/models.py
  enrollments/signals.py
  enrollments/tasks.py
  exams/api/serializers.py
  exams/api_admin/serializers.py
Labels: bug :bug:, enhancement :fire: :fire:

#225 pagination size from 1 to 10
  common/paginations.py
Labels: enhancement :fire: :fire:

#219 Add Exam Enrollment create, rank, filter
  README.md
  courses/api_admin/serializers.py
  courses/migrations/0006_auto_20220809_1559.py
  courses/models.py
  enrollments/admin.py
  enrollments/api/serializers.py
  enrollments/api/utils.py
  enrollments/api_admin/serializers.py
  enrollments/api_admin/urls.py
  enrollments/api_admin/views.py
  enrollments/filters.py
  enrollments/models.py
  enrollments/signals.py
  enrollments/tasks.py
  exams/api_admin/serializers.py
Labels: enhancement :fire: :fire:

#228 Course revert migration for duration migration error
  courses/migrations/0006_auto_20220816_1542.py
  courses/migrations/0007_course_duration.py
Labels: bug :bug:

#229 migration error fix
  courses/migrations/0006_auto_20220816_1542.py
  courses/migrations/0007_course_duration.py
Labels: deployment :flight_departure:

#231 Add new exam date and examiee in overview of exam
  enrollments/admin.py
  exams/api_admin/serializers.py
  exams/api_admin/urls.py
  exams/api_admin/views.py
Labels: enhancement :fire: :fire:

#232 exam overview deploy
  enrollments/admin.py
  exams/api_admin/serializers.py
  exams/api_admin/urls.py
  exams/api_admin/views.py
Labels: deployment :flight_departure:

#233 Exam template ordering and make query fast
  accounts/migrations/0008_alter_user_username.py
  accounts/models.py
  apex/settings.py
  apex/urls.py
  enrollments/models.py
  exams/migrations/0023_alter_examtemplate_options.py
  exams/models.py
Labels: enhancement :fire: :fire:

#234 Deploy
  accounts/migrations/0008_alter_user_username.py
  accounts/models.py
  apex/settings.py
  apex/urls.py
  enrollments/models.py
  exams/migrations/0023_alter_examtemplate_options.py
  exams/models.py
Labels: deployment :flight_departure:

#235 Update debug toolbar
  requirements.txt
Labels: bug :bug:

#236 Develop
  requirements.txt
Labels: deployment :flight_departure:

#238 Exam Session admin add feature
  enrollments/admin.py
Labels: enhancement :fire: :fire:

#239 Deploy
  enrollments/admin.py
Labels: deployment :flight_departure:

#240 Optimizing query of exam session and enrollment
  enrollments/admin.py
  enrollments/models.py
Labels: enhancement :fire: :fire:

#241 deploy
  enrollments/admin.py
  enrollments/models.py
Labels: deployment :flight_departure:

#242 User odering and update pagination
  accounts/api_admin/serializers.py
  accounts/api_admin/views.py
  attendance/api/views.py
  courses/api/views.py
  courses/api_admin/views.py
Labels: enhancement :fire: :fire:

#243 Deploy
  accounts/api_admin/serializers.py
  accounts/api_admin/views.py
  attendance/api/views.py
  courses/api/views.py
  courses/api_admin/views.py
Labels: deployment :flight_departure:

#247 Payment feature
  apex/settings.py
  common/utils.py
  payments/__init__.py
  payments/admin.py
  payments/api/__init__.py
  payments/api/serializers.py
  payments/api/urls.py
  payments/api/views.py
  payments/apps.py
  payments/gateways/__init__.py
  payments/gateways/base.py
  payments/gateways/esewa/__init__.py
  payments/gateways/esewa/pay.py
  payments/gateways/factory.py
  payments/gateways/khalti/__init__.py
  payments/gateways/khalti/pay.py
  payments/gateways/register.py
  payments/migrations/0001_initial.py
  payments/migrations/__init__.py
  payments/models.py
  payments/templates/payments/payment_info.html
  payments/templates/payments/payment_success.html
  payments/tests.py
  payments/views.py
Labels: enhancement :fire: :fire:

#248 Add Rank and Negative marks in enrollments
  enrollments/api/utils.py
  enrollments/migrations/0040_examthroughenrollment_negative_score.py
  enrollments/models.py
  enrollments/tasks.py
Labels: enhancement :fire: :fire:

#250 Rotate refresh token
  apex/settings.py
Labels: bug :bug:

#251 Rotate refresh token
  apex/settings.py
Labels: enhancement :fire: :fire:

#249 Add Signals to change EnrollmentStatus after payment
  enrollments/api/serializers.py
  enrollments/api_admin/serializers.py
  enrollments/models.py
  payments/apps.py
  payments/signals.py
Labels: enhancement :fire: :fire:

#255 Deploy
  .vscode/settings.json
  apex/settings.py
  common/utils.py
  courses/api/permissions.py
  courses/api/serializers.py
  courses/api/urls.py
  courses/api/views.py
  courses/migrations/0008_alter_course_description.py
  courses/models.py
  enrollments/api/serializers.py
  enrollments/api/urls.py
  enrollments/api/utils.py
  enrollments/api/views.py
  enrollments/api_admin/serializers.py
  enrollments/migrations/0040_examthroughenrollment_negative_score.py
  enrollments/models.py
  enrollments/tasks.py
  notes/api/serializers.py
  notes/api/urls.py
  notes/api/views.py
  payments/__init__.py
  payments/admin.py
  payments/api/__init__.py
  payments/api/serializers.py
  payments/api/urls.py
  payments/api/views.py
  payments/apps.py
  payments/gateways/__init__.py
  payments/gateways/base.py
  payments/gateways/esewa/__init__.py
  payments/gateways/esewa/pay.py
  payments/gateways/factory.py
  payments/gateways/khalti/__init__.py
  payments/gateways/khalti/pay.py
  payments/gateways/register.py
  payments/migrations/0001_initial.py
  payments/migrations/__init__.py
  payments/models.py
  payments/signals.py
  payments/templates/payments/payment_info.html
  payments/templates/payments/payment_success.html
  payments/tests.py
  payments/views.py
Labels: deployment :flight_departure:
