Repository atharvatechnology/apex-backend, pull requests merged in 2022-07, with the labels that each got.

#194 CRUD for exams and exam templates
  exams/api/serializers.py
  exams/api/views.py
  exams/api_admin/serializers.py
  exams/api_admin/urls.py
  exams/api_admin/views.py
  exams/migrations/0020_alter_question_section.py
  exams/models.py
Labels: enhancement :fire: :fire:

#197 Bug solution in enrollment serializer
  enrollments/api/serializers.py
Labels: bug :bug:

#198 View mini examtemplate for dropdown menu.
  apex/settings.py
  exams/api_admin/serializers.py
  exams/api_admin/urls.py
  exams/api_admin/views.py
Labels: enhancement :fire: :fire:

#195 Course and Course Catgeory CRUD for admin
  apex/urls.py
  courses/api/serializers.py
  courses/api/urls.py
  courses/api/views.py
  courses/api_admin/__init__.py
  courses/api_admin/serializers.py
  courses/api_admin/urls.py
  courses/api_admin/views.py
  courses/migrations/0004_auto_20220629_0953.py
  courses/migrations/0005_merge_20220701_1042.py
  courses/models.py
Labels: enhancement :fire: :fire:

#199 Solves bug contained in coursethroughenrollment create serializer
  enrollments/admin.py
  enrollments/api/serializers.py
  enrollments/migrations/0022_alter_coursethroughenrollment_completed_date.py
  enrollments/migrations/0023_alter_coursethroughenrollment_completed_date.py
Labels: bug :bug:

#203 Remove delete task.
  enrollments/models.py
  exams/api_admin/serializers.py
Labels: enhancement :fire: :fire:

#205 Notes,content,recorded video admin CRUD
  apex/urls.py
  notes/admin.py
  notes/api/urls.py
  notes/api/views.py
  notes/api_admin/__init__.py
  notes/api_admin/serializers.py
  notes/api_admin/urls.py
  notes/api_admin/views.py
  notes/migrations/0007_auto_20220630_1146.py
  notes/migrations/0008_auto_20220701_1126.py
  notes/models.py
Labels: enhancement :fire: :fire:

#206 Session Admin CRUD with some validation.
  apex/urls.py
  common/api/serializers.py
  enrollments/api/urls.py
  enrollments/api/views.py
  enrollments/api_admin/__init__.py
  enrollments/api_admin/serializers.py
  enrollments/api_admin/urls.py
  enrollments/api_admin/views.py
  enrollments/migrations/0024_alter_session_options.py
  enrollments/models.py
  enrollments/signals.py
Labels: enhancement :fire: :fire:

#207 Admin panel and some bug fixes
  .gitignore
  apex/settings.py
  apex/urls.py
  common/api/serializers.py
  courses/admin.py
  courses/api/serializers.py
  courses/api/urls.py
  courses/api/views.py
  courses/api_admin/__init__.py
  courses/api_admin/serializers.py
  courses/api_admin/urls.py
  courses/api_admin/views.py
  courses/migrations/0004_alter_coursecategory_options.py
  courses/migrations/0004_auto_20220629_0953.py
  courses/migrations/0005_merge_20220701_1042.py
  courses/models.py
  enrollments/admin.py
  enrollments/api/serializers.py
  enrollments/api/urls.py
  enrollments/api/views.py
  enrollments/api_admin/__init__.py
  enrollments/api_admin/serializers.py
  enrollments/api_admin/urls.py
  enrollments/api_admin/views.py
  enrollments/migrations/0020_alter_coursethroughenrollment_options.py
  enrollments/migrations/0021_auto_20220629_1419.py
  enrollments/migrations/0022_alter_coursethroughenrollment_completed_date.py
  enrollments/migrations/0023_alter_coursethroughenrollment_completed_date.py
  enrollments/migrations/0024_alter_session_options.py
  enrollments/models.py
  enrollments/signals.py
  exams/api/serializers.py
  exams/api/urls.py
  exams/api/views.py
  exams/api_admin/__init__.py
  exams/api_admin/serializers.py
  exams/api_admin/urls.py
  exams/api_admin/validators.py
  exams/api_admin/views.py
  exams/migrations/0020_alter_question_section.py
  exams/models.py
  notes/admin.py
  notes/api/urls.py
  notes/api/views.py
  notes/api_admin/__init__.py
  notes/api_admin/serializers.py
  notes/api_admin/urls.py
  notes/api_admin/views.py
  notes/migrations/0007_auto_20220630_1146.py
  notes/migrations/0008_auto_20220701_1126.py
  notes/models.py
Labels: deployment :flight_departure:

#209 Add permission class on missing views of admin
  exams/api_admin/views.py
  notes/api_admin/views.py
Labels: enhancement :fire: :fire:

#210 Deployment missing permission
  exams/api_admin/views.py
  notes/api_admin/views.py
Labels: deployment :flight_departure:

#211 Order questions by section
  exams/migrations/0021_alter_question_options.py
  exams/models.py
Labels: bug :bug:

#212 Moved published date validation to models and dynamic end_date session
  common/utils.py
  enrollments/admin.py
  enrollments/api_admin/serializers.py
  enrollments/migrations/0025_alter_session_end_date.py
  enrollments/models.py
  exams/admin.py
  exams/api_admin/serializers.py
  exams/api_admin/urls.py
  exams/api_admin/views.py
  exams/migrations/0022_examimage.py
  exams/models.py
Labels: enhancement :fire: :fire:

#213 Deployment with ckeditor and admin bug fix
  common/utils.py
  enrollments/admin.py
  enrollments/api_admin/serializers.py
  enrollments/migrations/0025_alter_session_end_date.py
  enrollments/models.py
  exams/admin.py
  exams/api_admin/serializers.py
  exams/api_admin/urls.py
  exams/api_admin/views.py
  exams/migrations/0021_alter_question_options.py
  exams/migrations/0022_examimage.py
  exams/models.py
Labels: deployment :flight_departure:

#217 Admin action to make user active
  accounts/admin.py
Labels: enhancement :fire: :fire:

#218 Deployment
  accounts/admin.py
  common/api/serializers.py
  enrollments/api_admin/serializers.py
  enrollments/api_admin/urls.py
  enrollments/api_admin/views.py
  exams/api_admin/serializers.py
  exams/api_admin/urls.py
  exams/api_admin/views.py
Labels: deployment :flight_departure:
