Repository atharvatechnology/apex-backend, pull requests merged in 2022-09, with the labels that each got.

#268 QR code generated during user signup.
  .isort.cfg
  accounts/migrations/0009_profile_qr_code.py
  accounts/migrations/0010_alter_profile_qr_code.py
  accounts/migrations/0011_alter_profile_qr_code.py
  accounts/migrations/0012_auto_20220830_1547.py
  accounts/models.py
  common/utils.py
  requirements.txt
Labels: feature :new:

#274 Remove Exam status and related work attached with it
  enrollments/api/serializers.py
  enrollments/api/utils.py
  enrollments/api_admin/serializers.py
  enrollments/models.py
  enrollments/signals.py
  exams/admin.py
  exams/api/serializers.py
  exams/api/urls.py
  exams/api/views.py
  exams/api_admin/serializers.py
  exams/migrations/0024_remove_exam_status.py
  exams/models.py
Labels: enhancement :fire: :fire:

#284 Deployment
  .isort.cfg
  accounts/api/serializers.py
  accounts/migrations/0009_profile_qr_code.py
  accounts/migrations/0010_alter_profile_qr_code.py
  accounts/migrations/0011_alter_profile_qr_code.py
  accounts/migrations/0012_auto_20220830_1547.py
  accounts/models.py
  apex/settings.py
  common/utils.py
  enrollments/api/serializers.py
  enrollments/api/utils.py
  enrollments/api_admin/serializers.py
  enrollments/models.py
  enrollments/signals.py
  exams/admin.py
  exams/api/serializers.py
  exams/api/urls.py
  exams/api/views.py
  exams/api_admin/serializers.py
  exams/migrations/0024_remove_exam_status.py
  exams/models.py
  requirements.txt
Labels: deployment :flight_departure:

#282 Add Notification Feature
  .gitignore
  .isort.cfg
  apex/.env.template
  apex/settings.py
  apex/urls.py
  notifications/__init__.py
  notifications/admin.py
  notifications/api_admin/__init__.py
  notifications/api_admin/serializers.py
  notifications/api_admin/urls.py
  notifications/api_admin/views.py
  notifications/apps.py
  notifications/migrations/0001_initial.py
  notifications/migrations/__init__.py
  notifications/models.py
  requirements.txt
Labels: enhancement :fire: :fire:

#290 Add Profile Update and User Retrieve
  accounts/api/serializers.py
  accounts/api/urls.py
  accounts/api/views.py
Labels: enhancement :fire: :fire:

#289 Integrate zoom meeting for courses
  .isort.cfg
  apex/.env.template
  apex/settings.py
  apex/urls.py
  courses/api/serializers.py
  enrollments/api/serializers.py
  enrollments/api_admin/serializers.py
  enrollments/migrations/0041_session_name.py
  enrollments/models.py
  meetings/__init__.py
  meetings/admin.py
  meetings/api/__init__.py
  meetings/api/serializers.py
  meetings/api/urls.py
  meetings/api/views.py
  meetings/api_admin/__init__.py
  meetings/api_admin/serializers.py
  meetings/api_admin/urls.py
  meetings/api_admin/views.py
  meetings/apps.py
  meetings/migrations/0001_initial.py
  meetings/migrations/0002_auto_20220912_1611.py
  meetings/migrations/0003_auto_20220914_1252.py
  meetings/migrations/0004_auto_20220914_1540.py
  meetings/migrations/0005_auto_20220919_1617.py
  meetings/migrations/0006_auto_20220925_1831.py
  meetings/migrations/__init__.py
  meetings/models.py
  meetings/providers/__init__.py
  meetings/providers/base.py
  meetings/providers/factory.py
  meetings/providers/register.py
  meetings/providers/zoom/__init__.py
  meetings/providers/zoom/meet.py
  meetings/providers/zoom/utils.py
  meetings/tests.py
  meetings/views.py
Labels: enhancement :fire: :fire:

#291 env variable key error fix
  apex/.env.template
Labels: enhancement :fire: :fire:

#295 Courses zoom meet
  apex/urls.py
  courses/api/permissions.py
  courses/models.py
  exams/api/permissions.py
  meetings/api_admin/serializers.py
  meetings/migrations/0007_alter_meeting_password.py
  meetings/models.py
  meetings/providers/zoom/meet.py
Labels: bug :bug:, enhancement :fire: :fire:

#296 Deploy
  .gitignore
  .isort.cfg
  accounts/api/serializers.py
  accounts/api/urls.py
  accounts/api/views.py
  apex/.env.template
  apex/settings.py
  apex/urls.py
  courses/api/permissions.py
  courses/api/serializers.py
  courses/models.py
  enrollments/api/serializers.py
  enrollments/api_admin/serializers.py
  enrollments/migrations/0041_session_name.py
  enrollments/models.py
  exams/api/permissions.py
  meetings/__init__.py
  meetings/admin.py
  meetings/api/__init__.py
  meetings/api/serializers.py
  meetings/api/urls.py
  meetings/api/views.py
  meetings/api_admin/__init__.py
  meetings/api_admin/serializers.py
  meetings/api_admin/urls.py
  meetings/api_admin/views.py
  meetings/apps.py
  meetings/migrations/0001_initial.py
  meetings/migrations/0002_auto_20220912_1611.py
  meetings/migrations/0003_auto_20220914_1252.py
  meetings/migrations/0004_auto_20220914_1540.py
  meetings/migrations/0005_auto_20220919_1617.py
  meetings/migrations/0006_auto_20220925_1831.py
  meetings/migrations/0007_alter_meeting_password.py
  meetings/migrations/__init__.py
  meetings/models.py
  meetings/providers/__init__.py
  meetings/providers/base.py
  meetings/providers/factory.py
  meetings/providers/register.py
  meetings/providers/zoom/__init__.py
  meetings/providers/zoom/meet.py
  meetings/providers/zoom/utils.py
  meetings/tests.py
  meetings/views.py
  notifications/__init__.py
  notifications/admin.py
  notifications/api_admin/__init__.py
  notifications/api_admin/serializers.py
  notifications/api_admin/urls.py
  notifications/api_admin/views.py
  notifications/apps.py
  notifications/migrations/0001_initial.py
  notifications/migrations/__init__.py
  notifications/models.py
  requirements.txt
Labels: deployment :flight_departure:

#298 Deploy
  enrollments/api/serializers.py
Labels: deployment :flight_departure:

#299 Infocenter feature for webpage
  apex/settings.py
  apex/urls.py
  infocenter/__init__.py
  infocenter/admin.py
  infocenter/api/__init__.py
  infocenter/api/serializers.py
  infocenter/api/urls.py
  infocenter/api/views.py
  infocenter/api_admin/__init__.py
  infocenter/api_admin/serializers.py
  infocenter/api_admin/urls.py
  infocenter/api_admin/views.py
  infocenter/apps.py
  infocenter/migrations/0001_initial.py
  infocenter/migrations/0002_auto_20220928_1520.py
  infocenter/migrations/__init__.py
  infocenter/models.py
  infocenter/tests.py
  infocenter/views.py
Labels: feature :new:

#300 Deployment
  apex/settings.py
  apex/urls.py
  infocenter/__init__.py
  infocenter/admin.py
  infocenter/api/__init__.py
  infocenter/api/serializers.py
  infocenter/api/urls.py
  infocenter/api/views.py
  infocenter/api_admin/__init__.py
  infocenter/api_admin/serializers.py
  infocenter/api_admin/urls.py
  infocenter/api_admin/views.py
  infocenter/apps.py
  infocenter/migrations/0001_initial.py
  infocenter/migrations/0002_auto_20220928_1520.py
  infocenter/migrations/__init__.py
  infocenter/models.py
  infocenter/tests.py
  infocenter/views.py
Labels: deployment :flight_departure:

#301 Notification list and Notification message params
  apex/urls.py
  notifications/api_admin/urls.py
  notifications/api_admin/views.py
Labels: enhancement :fire: :fire:

#302 Deployment
  apex/urls.py
  notifications/api_admin/urls.py
  notifications/api_admin/views.py
Labels: deployment :flight_departure:

#275 Add verification for course enrollment with qr scan
  accounts/migrations/0012_auto_20220830_1547.py
  attendance/admin.py
  attendance/api/migrations/__init__.py
  attendance/api/serializers.py
  attendance/api/tests.py
  attendance/api/urls.py
  attendance/api/views.py
  common/utils.py
  enrollments/api/serializers.py
  enrollments/api/urls.py
  enrollments/api/views.py
  enrollments/api_admin/serializers.py
  enrollments/api_admin/urls.py
  enrollments/api_admin/views.py
Labels: enhancement :fire: :fire:

#304 Retrieve course enrollment status and calculate total enrollment price.
  courses/api/serializers.py
  enrollments/api/serializers.py
Labels: enhancement :fire: :fire:

#305 Deploy
  accounts/migrations/0012_auto_20220830_1547.py
  attendance/admin.py
  attendance/api/migrations/__init__.py
  attendance/api/serializers.py
  attendance/api/tests.py
  attendance/api/urls.py
  attendance/api/views.py
  common/utils.py
  courses/api/serializers.py
  enrollments/api/serializers.py
  enrollments/api/urls.py
  enrollments/api/views.py
  enrollments/api_admin/serializers.py
  enrollments/api_admin/urls.py
  enrollments/api_admin/views.py
Labels: deployment :flight_departure:
