Repository atharvatechnology/apex-backend, pull requests merged in 2022-05, with the labels that each got.

#17 Created Custom User model
  .github/ISSUE_TEMPLATE/feature_request.md
  .pre-commit-config.yaml
  accounts/__init__.py
  accounts/admin.py
  accounts/apps.py
  accounts/migrations/0001_initial.py
  accounts/migrations/__init__.py
  accounts/models.py
  accounts/tests.py
  apex/asgi.py
  apex/settings.py
  apex/urls.py
  apex/wsgi.py
  manage.py
  requirements.txt
  setup.cfg
Labels: enhancement :fire: :fire:

#14 Add common app for code reusability
  common/__init__.py
  common/admin.py
  common/apps.py
  common/migrations/__init__.py
  common/models.py
  common/tests.py
Labels: enhancement :fire: :fire:

#24 Install drf and update requirements.txt
  apex/settings.py
  requirements.txt
Labels: enhancement :fire: :fire:

#21 Update Username usermodel
  .pre-commit-config.yaml
  accounts/migrations/0002_alter_user_username.py
  accounts/models.py
  accounts/validators.py
  setup.cfg
Labels: bug :bug:

#30 User models and Authentication, Install diffrent packages
  .isort.cfg
  .pre-commit-config.yaml
  accounts/admin.py
  accounts/api/__init__.py
  accounts/api/otp.py
  accounts/api/serializers.py
  accounts/api/urls.py
  accounts/api/views.py
  accounts/migrations/0003_user_otp_counter.py
  accounts/migrations/0004_user_otp_user_otp_generate_time.py
  accounts/models.py
  apex/settings.py
  apex/urls.py
  requirements.txt
  setup.cfg
Labels: enhancement :fire: :fire:

#18 Create models for notes app
  apex/settings.py
  common/models.py
  notes/__init__.py
  notes/admin.py
  notes/apps.py
  notes/migrations/0001_initial.py
  notes/migrations/__init__.py
  notes/models.py
  notes/tests.py
  notes/views.py
Labels: enhancement :fire: :fire:

#31 Add exam models.
  apex/settings.py
  common/validators.py
  exams/__init__.py
  exams/admin.py
  exams/apps.py
  exams/migrations/__init__.py
  exams/models.py
  exams/tests.py
  exams/views.py
  pyproject.toml
Labels: enhancement :fire: :fire:

#34 Extract common things of creator into base classes.
  apex/settings.py
  common/api/__init__.py
  common/api/serializers.py
  common/api/views.py
  exams/migrations/0001_initial.py
  exams/migrations/0002_section_question_option.py
  exams/models.py
Labels: enhancement :fire: :fire:, help wanted

#36 Migrate exam models.
  exams/migrations/0003_alter_exam_category.py
  exams/migrations/0004_remove_examtemplate_max_score_and_more.py
  exams/models.py
Labels: enhancement :fire: :fire:

#41 Add sections in question.
  .isort.cfg
  apex/settings.py
  exams/migrations/0005_question_section.py
  exams/models.py
Labels: enhancement :fire: :fire:

#33 Add CRUD in api for the notes app
  .isort.cfg
  apex/settings.py
  apex/urls.py
  notes/admin.py
  notes/api/serializers.py
  notes/api/urls.py
  notes/api/views.py
  notes/models.py
  requirements.txt
Labels: enhancement :fire: :fire:

#47 Customized exam admin with nested_admin package
  .isort.cfg
  apex/settings.py
  exams/admin.py
  templates/inlines/stacked.html
  templates/inlines/tabular.html
Labels: enhancement :fire: :fire:

#49 Update requirements for nested admin
  requirements.txt
Labels: bug :bug:

#51 Authentication and exam admin customization.
  apex/middleware.py
  apex/settings.py
  exams/admin.py
Labels: enhancement :fire: :fire:

#52 Modification of user login path and config simple jwt and update middleware
  apex/middleware.py
  apex/settings.py
  apex/urls.py
Labels: enhancement :fire: :fire:

#53 Model enrollment app.
  apex/settings.py
  enrollments/__init__.py
  enrollments/admin.py
  enrollments/apps.py
  enrollments/migrations/0001_initial.py
  enrollments/migrations/0002_remove_enrollment_created_by_and_more.py
  enrollments/migrations/0003_session_exam_alter_session_status.py
  enrollments/migrations/0004_alter_enrollment_student.py
  enrollments/migrations/__init__.py
  enrollments/models.py
  enrollments/tests.py
  enrollments/views.py
  exams/api/serializers.py
  exams/models.py
Labels: enhancement :fire: :fire:

#54 Notes admin panel is used to add notes and contents for a course
  apex/settings.py
  apex/urls.py
  notes/admin.py
Labels: enhancement :fire: :fire:

#55 OTP reset password verified with frontend
  accounts/api/serializers.py
  accounts/api/urls.py
  accounts/api/views.py
  accounts/models.py
  apex/settings.py
Labels: enhancement :fire: :fire:

#57 Manage environ with djagno-environ and update requirements
  .isort.cfg
  apex/.env.template
  apex/settings.py
  requirements.txt
  static/.gitkeep
Labels: enhancement :fire: :fire:

#59 Dockerization of the system with update requirements.txt
  .dockerignore
  Dockerfile
  apex/settings.py
  entrypoint.sh
  gunicorn-config.py
  requirements.txt
Labels: enhancement :fire: :fire:

#63 Add CRUD for enrollments.
  apex/urls.py
  common/api/mixin.py
  enrollments/api/__init__.py
  enrollments/api/serializers.py
  enrollments/api/urls.py
  enrollments/api/utils.py
  enrollments/api/views.py
  exams/api/serializers.py
  exams/api/views.py
Labels: enhancement :fire: :fire:

#61 Enrollment admin Created
  enrollments/admin.py
Labels: enhancement :fire: :fire:

#69 Solved issue of swagger
  apex/urls.py
Labels: bug :bug:

#75 add psql requirements
  requirements.txt
Labels: enhancement :fire: :fire:

#77 Update csrf trusted origin using settings for csrf error fix
  apex/.env.template
  apex/settings.py
Labels: bug :bug:

#79 Add JWT_AUTH_SECURE env for jwt secure access on cookies for chrome
  apex/.env.template
  apex/settings.py
Labels: deployment :flight_departure:
