Repository atharvatechnology/apex-backend, pull requests merged in 2023-04, with the labels that each got.

#442 Get total seconds from access_token fix
  accounts/api/views.py
Labels: bug :bug:

#443 Indicate joinable meetings with zoom webhook.
  .vscode/settings.json
  apex/settings.py
  courses/api/serializers.py
  courses/api/views.py
  enrollments/api/views.py
  enrollments/tasks.py
  meetings/api/serializers.py
  meetings/api/urls.py
  meetings/api/views.py
  meetings/api_admin/serializers.py
  meetings/migrations/0008_meeting_meeting_status.py
  meetings/models.py
Labels: enhancement :fire: :fire:

#444 Deploy webhook and single signon.
  .vscode/settings.json
  accounts/api/views.py
  apex/settings.py
  courses/api/serializers.py
  courses/api/views.py
  enrollments/api/views.py
  enrollments/tasks.py
  meetings/api/serializers.py
  meetings/api/urls.py
  meetings/api/views.py
  meetings/api_admin/serializers.py
  meetings/migrations/0008_meeting_meeting_status.py
  meetings/models.py
Labels: deployment :flight_departure:

#459 Fix authentication failed error by deleteing cookies
  accounts/signals.py
  apex/middleware.py
Labels: bug :bug:

#458 Change permission of course retrive api before enroll
  courses/api/views.py
Labels: bug :bug:

#446 Don't access request data before accessing request body.
  apex/middleware.py
  apex/settings.py
  courses/api/urls.py
  enrollments/api/serializers.py
  enrollments/api/utils.py
  enrollments/api/views.py
  enrollments/api_admin/serializers.py
  enrollments/signals.py
  exams/api_common/serializers.py
  meetings/api/serializers.py
  meetings/api/views.py
  meetings/api_admin/serializers.py
  meetings/api_admin/views.py
Labels: bug :bug:, enhancement :fire: :fire:

#464 fix Qr, Attendance and login user
  .vscode/settings.json
  accounts/api_admin/urls.py
  accounts/api_admin/views.py
  accounts/models.py
  apex/middleware.py
  attendance/api/serializers.py
  attendance/api/views.py
  discussion/api_admin/views.py
Labels: bug :bug:

#466 Apex bug fix.
  .vscode/settings.json
  accounts/api_admin/urls.py
  accounts/api_admin/views.py
  accounts/models.py
  accounts/signals.py
  apex/middleware.py
  apex/settings.py
  attendance/api/serializers.py
  attendance/api/views.py
  courses/api/urls.py
  courses/api/views.py
  discussion/api_admin/views.py
  enrollments/api/serializers.py
  enrollments/api/utils.py
  enrollments/api/views.py
  enrollments/api_admin/serializers.py
  enrollments/signals.py
  exams/api_common/serializers.py
  meetings/api/serializers.py
  meetings/api/views.py
  meetings/api_admin/serializers.py
  meetings/api_admin/views.py
Labels: enhancement :fire: :fire:, deployment :flight_departure:

#469 Hotfix of attendance, notification, report and 498 status code
  apex/middleware.py
  attendance/api/serializers.py
  attendance/api/views.py
  attendance/filters.py
  attendance/migrations/0014_alter_teacherattendancedetail_remarks.py
  attendance/models.py
  notifications/migrations/0002_alter_notificationmessage_options.py
  notifications/models.py
  report/tabledata.py
Labels: enhancement :fire: :fire:

#470 Deploy bug fixes to attendance and enrollment payment feature
  apex/middleware.py
  attendance/api/serializers.py
  attendance/api/views.py
  attendance/filters.py
  attendance/migrations/0014_alter_teacherattendancedetail_remarks.py
  attendance/models.py
  enrollments/api_admin/serializers.py
  notifications/migrations/0002_alter_notificationmessage_options.py
  notifications/models.py
  payments/api_admin/serializers.py
  payments/api_admin/urls.py
  payments/api_admin/views.py
  payments/signals.py
  report/tabledata.py
Labels: deployment :flight_departure:

#471 Add permission of cashier in notification and counselor api
  accounts/api_admin/views.py
  counseling/api_admin/views.py
  notifications/api_admin/views.py
Labels: enhancement :fire: :fire:

#472 Deployment of updated cashier permission.
  accounts/api_admin/views.py
  counseling/api_admin/views.py
  notifications/api_admin/views.py
Labels: deployment :flight_departure:

#474 Deployment for revenue dashboard amount decimal size
  dashboard/api_admin/serializers.py
Labels: deployment :flight_departure:

#475 Register payment model in admin
  payments/admin.py
Labels: enhancement :fire: :fire:

#476 Deploy payment model register in admin
  payments/admin.py
Labels: enhancement :fire: :fire:
