Repository atharvatechnology/apex-backend, pull requests merged in 2023-01, with the labels that each got.

#388 error in revenue tred calculation
  dashboard/api_admin/views.py
Labels: enhancement :fire: :fire:

#389 deployment
  accounts/api_admin/views.py
  attendance/api_admin/views.py
  bannerad/api_admin/views.py
  common/api/views.py
  common/permissions.py
  counseling/api_admin/views.py
  courses/api_admin/views.py
  dashboard/api_admin/serializers.py
  dashboard/api_admin/urls.py
  dashboard/api_admin/views.py
  enrollments/api_admin/views.py
  exams/api_admin/views.py
  infocenter/api_admin/views.py
  meetings/api_admin/views.py
  notes/api_admin/views.py
  notifications/api_admin/views.py
  payments/api_admin/views.py
  physicalbook/api_admin/views.py
Labels: deployment :flight_departure:

#390 divisible by zero error
  dashboard/api_admin/views.py
Labels: enhancement :fire: :fire:

#391 Deployment
  dashboard/api_admin/views.py
Labels: deployment :flight_departure:

#386 Filter exam list using user interests
  accounts/api/serializers.py
  exams/api/views.py
Labels: enhancement :fire: :fire:

#392 Course field, enrollment by student code, enrollment exam serializer
  attendance/api/views.py
  courses/migrations/0012_alter_course_description.py
  courses/models.py
  enrollments/api/serializers.py
  enrollments/api/utils.py
  enrollments/api_admin/serializers.py
  enrollments/api_admin/urls.py
  enrollments/api_admin/views.py
  meetings/api/views.py
Labels: enhancement :fire: :fire:

#394 User Details of classes attended, exams attended and total number of classes and exams..
  enrollments/admin.py
  enrollments/api/serializers.py
  enrollments/api/urls.py
  enrollments/api/views.py
  enrollments/migrations/0044_auto_20230105_1626.py
  enrollments/models.py
  meetings/api/serializers.py
Labels: enhancement :fire: :fire:

#358 Report change and filters
  accounts/api/urls.py
  accounts/api/views.py
  accounts/api_admin/urls.py
  accounts/api_admin/views.py
  apex/urls.py
  attendance/api_admin/urls.py
  attendance/api_admin/views.py
  attendance/filters.py
  common/api/serializers.py
  common/api/views.py
  common/permissions.py
  common/report.py
  courses/migrations/0013_alter_course_duration.py
  courses/models.py
  enrollments/api/tasks.py
  enrollments/api/urls.py
  enrollments/api/views.py
  enrollments/api_admin/serializers.py
  enrollments/api_admin/urls.py
  enrollments/api_admin/views.py
  enrollments/filters.py
  enrollments/models.py
  report/api_admin/__init__.py
  report/api_admin/serializers.py
  report/api_admin/urls.py
  report/tabledata.py
Labels: enhancement :fire: :fire:

#396 Handle error if not enrolled into the exam in trigger.
  exams/api/views.py
Labels: bug :bug:

#395 Bugs correction in Report
  common/api/serializers.py
  common/api/views.py
  common/report.py
Labels: bug :bug:

#397 Integration fix of banner ads
  bannerad/api/serializers.py
  bannerad/api/urls.py
  bannerad/api/views.py
  bannerad/api_admin/serializers.py
  bannerad/api_admin/urls.py
  bannerad/api_admin/views.py
  bannerad/migrations/0005_bannerad_category.py
  bannerad/migrations/0006_bannerad_title.py
  bannerad/models.py
Labels: enhancement :fire: :fire:

#399 Deployment
  accounts/api/urls.py
  accounts/api/views.py
  accounts/api_admin/urls.py
  accounts/api_admin/views.py
  apex/urls.py
  attendance/api_admin/urls.py
  attendance/api_admin/views.py
  attendance/filters.py
  bannerad/api/serializers.py
  bannerad/api/urls.py
  bannerad/api/views.py
  bannerad/api_admin/serializers.py
  bannerad/api_admin/urls.py
  bannerad/api_admin/views.py
  bannerad/migrations/0005_bannerad_category.py
  bannerad/migrations/0006_bannerad_title.py
  bannerad/models.py
  common/api/serializers.py
  common/api/views.py
  common/permissions.py
  common/report.py
  courses/migrations/0013_alter_course_duration.py
  courses/models.py
  dashboard/api/__init__.py
  dashboard/api/urls.py
  dashboard/api/views.py
  enrollments/admin.py
  enrollments/api/serializers.py
  enrollments/api/tasks.py
  enrollments/api/urls.py
  enrollments/api/views.py
  enrollments/api_admin/serializers.py
  enrollments/api_admin/urls.py
  enrollments/api_admin/views.py
  enrollments/filters.py
  enrollments/migrations/0044_auto_20230105_1626.py
  enrollments/models.py
  exams/api/views.py
  meetings/api/serializers.py
  report/api_admin/__init__.py
  report/api_admin/serializers.py
  report/api_admin/urls.py
  report/tabledata.py
Labels: deployment :flight_departure:

#402 stafftracking app and admin integration
  apex/settings.py
  apex/urls.py
  clock/consumers.py
  clock/routing.py
  stafftracking/__init__.py
  stafftracking/admin.py
  stafftracking/api_admin/__init__.py
  stafftracking/api_admin/serializers.py
  stafftracking/api_admin/urls.py
  stafftracking/api_admin/views.py
  stafftracking/apps.py
  stafftracking/migrations/0001_initial.py
  stafftracking/migrations/__init__.py
  stafftracking/models.py
Labels: enhancement :fire: :fire:

#403 Add indexing in username field of user model
  accounts/migrations/0020_alter_user_username.py
  accounts/models.py
Labels: enhancement :fire: :fire:

#404 Staff Tracking get data per user api for admin
  stafftracking/api_admin/urls.py
  stafftracking/api_admin/views.py
Labels: enhancement :fire: :fire:

#405 Deployment of Stafftracking and User username db-indexing
  .github/workflows/gcloud-upscale.yml
  accounts/api/serializers.py
  accounts/migrations/0020_alter_user_username.py
  accounts/models.py
  apex/settings.py
  apex/urls.py
  clock/consumers.py
  clock/routing.py
  courses/api/views.py
  stafftracking/__init__.py
  stafftracking/admin.py
  stafftracking/api_admin/__init__.py
  stafftracking/api_admin/serializers.py
  stafftracking/api_admin/urls.py
  stafftracking/api_admin/views.py
  stafftracking/apps.py
  stafftracking/migrations/0001_initial.py
  stafftracking/migrations/__init__.py
  stafftracking/models.py
Labels: deployment :flight_departure:

#406 Queryset filter using mixin in exams and courses
  common/api/mixin.py
  courses/api/views.py
  exams/api/views.py
Labels: enhancement :fire: :fire:

#407 CD on gcp
  .github/workflows/deploy-gcp.yml
Labels: enhancement :fire: :fire:

#408 Deployment
  .github/workflows/deploy-gcp.yml
  common/api/mixin.py
  courses/api/views.py
  exams/api/views.py
Labels: deployment :flight_departure:

#409 add Missing 'needs' field in deploy-gcp
  .github/workflows/deploy-gcp.yml
Labels: enhancement :fire: :fire:

#410 Deployment
  .github/workflows/deploy-gcp.yml
Labels: deployment :flight_departure:

#411 make main and live in same level
  .github/workflows/deploy-gcp.yml
Labels: deployment :flight_departure:

#412 Remove unwanted actions
  .github/workflows/deploy-gcp.yml
  .github/workflows/dev.yml
  .github/workflows/main.yml
Labels: enhancement :fire: :fire:

#413 Create/check profile signal error fix
  accounts/signals.py
Labels: enhancement :fire: :fire:

#414 Load apps befor any other imports.
  apex/asgi.py
Labels: bug :bug:, enhancement :fire: :fire:
