Repository atharvatechnology/apex-backend, pull requests merged in 2023-02, with the labels that each got.

#417 Optimization of exam list, course list , enrollment list
  accounts/models.py
  common/api/mixin.py
  courses/api/serializers.py
  courses/api/views.py
  enrollments/api/serializers.py
  enrollments/api/views.py
  exams/api/serializers.py
  exams/api/views.py
Labels: enhancement :fire: :fire:

#418 Optimize requested with respect to db.
  .gitignore
  README.md
  apex/settings.py
  apex/urls.py
  enrollments/api/serializers.py
  enrollments/api/utils.py
  enrollments/api/views.py
  enrollments/models.py
  exams/api/permissions.py
  exams/api/serializers.py
  exams/api/views.py
Labels: enhancement :fire: :fire:

#419 Optimization of db queries in exam urls.
  .gitignore
  README.md
  accounts/models.py
  apex/settings.py
  apex/urls.py
  common/api/mixin.py
  courses/api/serializers.py
  courses/api/views.py
  enrollments/api/serializers.py
  enrollments/api/utils.py
  enrollments/api/views.py
  enrollments/models.py
  exams/api/permissions.py
  exams/api/serializers.py
  exams/api/views.py
Labels: enhancement :fire: :fire:

#420 Merge changes from main.
  apex/asgi.py
Labels: deployment :flight_departure:

#422 Fix bug in submit
  enrollments/api/serializers.py
Labels: bug :bug:, deployment :flight_departure:

#423 Deployment
  enrollments/api/serializers.py
Labels: bug :bug:, deployment :flight_departure:

#424 Count the different resources provided by apex.
  infocenter/api/urls.py
  infocenter/api/views.py
Labels: enhancement :fire: :fire:

#426 Raise validation error instead of exception in save.
  enrollments/api/serializers.py
Labels: bug :bug:, enhancement :fire: :fire:

#427 Deployment
  enrollments/api/serializers.py
  infocenter/api/urls.py
  infocenter/api/views.py
Labels: deployment :flight_departure:
