Repository atharvatechnology/apex-backend, pull requests merged in 2023-03, with the labels that each got.

#429 Create api for enrollment in student detail view admin
  apex/settings.py
  enrollments/api_admin/serializers.py
  enrollments/api_admin/urls.py
  enrollments/api_admin/views.py
Labels: enhancement :fire: :fire:

#431 Deployment
  apex/settings.py
  enrollments/api_admin/serializers.py
  enrollments/api_admin/urls.py
  enrollments/api_admin/views.py
Labels: enhancement :fire: :fire:, deployment :flight_departure:

#428 Concurrent login block.
  .isort.cfg
  accounts/api/views.py
  apex/middleware.py
  apex/settings.py
  apex/urls.py
Labels: enhancement :fire: :fire:

#435 Use redis_url instead of config element for auth redis
  apex/settings.py
Labels: bug :bug:

#436 Deployment
  .isort.cfg
  accounts/api/views.py
  apex/middleware.py
  apex/settings.py
  apex/urls.py
Labels: deployment :flight_departure:

#433 Staff Tracking integration bug fix
  accounts/api_admin/serializers.py
  accounts/api_admin/views.py
  clock/consumers.py
  stafftracking/admin.py
  stafftracking/api_admin/serializers.py
  stafftracking/migrations/0002_auto_20230301_1504.py
  stafftracking/migrations/0003_staffconnectionstatus.py
  stafftracking/migrations/0004_staffconnectionstatus_is_enabled.py
  stafftracking/migrations/0005_alter_staffconnectionstatus_user.py
  stafftracking/models.py
Labels: enhancement :fire: :fire:

#416 Add Discussion Feature
  apex/settings.py
  apex/urls.py
  discussion/__init__.py
  discussion/admin.py
  discussion/api/__init__.py
  discussion/api/serializers.py
  discussion/api/urls.py
  discussion/api/views.py
  discussion/api_admin/__init__.py
  discussion/api_admin/serializers.py
  discussion/api_admin/urls.py
  discussion/api_admin/views.py
  discussion/apps.py
  discussion/migrations/0001_initial.py
  discussion/migrations/0002_alter_question_options.py
  discussion/migrations/__init__.py
  discussion/models.py
  discussion/permissions.py
  discussion/tests.py
  discussion/views.py
Labels: feature :new:

#437 Deployment
  accounts/api_admin/serializers.py
  accounts/api_admin/views.py
  apex/settings.py
  apex/urls.py
  clock/consumers.py
  discussion/__init__.py
  discussion/admin.py
  discussion/api/__init__.py
  discussion/api/serializers.py
  discussion/api/urls.py
  discussion/api/views.py
  discussion/api_admin/__init__.py
  discussion/api_admin/serializers.py
  discussion/api_admin/urls.py
  discussion/api_admin/views.py
  discussion/apps.py
  discussion/migrations/0001_initial.py
  discussion/migrations/0002_alter_question_options.py
  discussion/migrations/__init__.py
  discussion/models.py
  discussion/permissions.py
  discussion/tests.py
  discussion/views.py
  stafftracking/admin.py
  stafftracking/api_admin/serializers.py
  stafftracking/migrations/0002_auto_20230301_1504.py
  stafftracking/migrations/0003_staffconnectionstatus.py
  stafftracking/migrations/0004_staffconnectionstatus_is_enabled.py
  stafftracking/migrations/0005_alter_staffconnectionstatus_user.py
  stafftracking/models.py
Labels: deployment :flight_departure:

#438 Fix Serializer's Error
  discussion/api_admin/serializers.py
Labels: bug :bug:

#440 Fix User roles assignment, Attendance filter, single device login.
  accounts/api/views.py
  accounts/api_admin/serializers.py
  apex/middleware.py
  apex/settings.py
  attendance/filters.py
  common/utils.py
  enrollments/api_admin/serializers.py
Labels: bug :bug:, enhancement :fire: :fire:
