Repository atharvatechnology/apex-backend, pull requests merged in 2023-05, with the labels that each got.

#477 Create api to fetch my exams list
  exams/api/urls.py
  exams/api/views.py
Labels: enhancement :fire: :fire:

#478 Add subtopic field to physical book
  .vscode/settings.json
  courses/api/serializers.py
  enrollments/signals.py
  physicalbook/api/serializers.py
  physicalbook/api_admin/serializers.py
  physicalbook/migrations/0003_physicalbook_sub_topic.py
  physicalbook/models.py
Labels: enhancement :fire: :fire:

#479 deployment of physical books and exam list
  .vscode/settings.json
  courses/api/serializers.py
  enrollments/signals.py
  exams/api/urls.py
  exams/api/views.py
  physicalbook/api/serializers.py
  physicalbook/api_admin/serializers.py
  physicalbook/migrations/0003_physicalbook_sub_topic.py
  physicalbook/models.py
Labels: deployment :flight_departure:

#480 Bug fix of total question count of exam
  exams/api/serializers.py
Labels: bug :bug:, enhancement :fire: :fire:

#481 Bug fix of question count
  exams/api/serializers.py
Labels: deployment :flight_departure:

#482 Add distinct in my exam list query
  exams/api/views.py
Labels: enhancement :fire: :fire:

#483 deployment of my exam with distinct query
  exams/api/views.py
Labels: deployment :flight_departure:

#484 Send otp to user using celery.
  accounts/api/otp.py
  accounts/tasks.py
Labels: enhancement :fire: :fire:

#485 Deployment of send otp through celery
  accounts/api/otp.py
  accounts/tasks.py
Labels: deployment :flight_departure:

#486 Add new role for content creation of exam and course
  accounts/api_admin/views.py
  accounts/migrations/0021_alter_role_id.py
  accounts/models.py
  common/permissions.py
  courses/api_admin/views.py
  exams/api_admin/views.py
Labels: enhancement :fire: :fire:

#487 Grant permissions to content creator.
  accounts/api_admin/views.py
  accounts/migrations/0021_alter_role_id.py
  accounts/models.py
  common/api/views.py
  common/permissions.py
  courses/api_admin/views.py
  enrollments/api_admin/views.py
  exams/api_admin/views.py
  meetings/api_admin/views.py
  notes/api_admin/views.py
  report/api_admin/views.py
Labels: enhancement :fire: :fire:

#488 Deploy contencreator role feature.
  accounts/api_admin/views.py
  accounts/migrations/0021_alter_role_id.py
  accounts/models.py
  common/api/views.py
  common/permissions.py
  courses/api_admin/views.py
  enrollments/api_admin/views.py
  exams/api_admin/views.py
  meetings/api_admin/views.py
  notes/api_admin/views.py
  report/api_admin/views.py
Labels: enhancement :fire: :fire:, deployment :flight_departure:
